[versions]
openapiGenerator = "7.23.0"
pluginPublish = "2.1.1"
junit = "6.1.2"

[libraries]
openapi-generator-gradle-plugin = { module = "org.openapitools:openapi-generator-gradle-plugin", version.ref = "openapiGenerator" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
