name: Dependabot Auto-Merge

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-merge:
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v2
    secrets:
      GITHUB_PAT: ${{ secrets.DEPENDABOT_AUTO_MERGE_PAT }}
